executable              = <executionScript.sh>
# Get the environment from the submission host?
#arguments               = $Fnx(filename)
output                  = $(ClusterId).$(ProcId).out
error                   = $(ClusterId).$(ProcId).err
log                     = $(ClusterID).log
getenv                  = True
#should_transfer_files   = YES
#when_to_transfer_output = ON_EXIT
accounting_group = group_atlas.tier3.yale
Queue 1

